"""
Generate static HTML snapshots of dashboard charts for GitHub Pages.

Usage:
    python scripts/export_snapshot.py

Output:
    docs/snapshots/china_activity.html
    docs/snapshots/japan_activity.html

Run from the repo root. Requires haver-data to be accessible (default path or
HAVER_DATA_REPO env var set).
"""

import sys
import pathlib
import warnings

# Make src/ importable when running from repo root
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from src.monitor_config import CHINA, JAPAN
from src.page_utils import build_theme_df, standardize_dataframe, compute_contributions
from src.factor_analysis import extract_factor
from src.charts import (
    factor_chart, theme_chart, surprise_heatmap, contributions_radial,
)

DOCS_DIR = pathlib.Path(__file__).parent.parent / "docs" / "snapshots"
DOCS_DIR.mkdir(parents=True, exist_ok=True)

EXPORTS = [
    ("China", CHINA, "activity", "china_activity.html"),
    ("Japan", JAPAN, "activity", "japan_activity.html"),
]


def _pca_cols(indicators: list) -> list:
    from src.page_utils import display_label
    return [
        display_label(ind["label"], ind["transform"])
        for ind in indicators if ind.get("in_pca", True)
    ]


def export_activity(country: str, config: dict, out_file: pathlib.Path) -> None:
    indicators = config["activity"]
    df = build_theme_df(indicators)
    if df.empty:
        warnings.warn(f"No data for {country} activity — skipping.")
        return

    pca_cols = _pca_cols(indicators)
    result = extract_factor(df, remove_outliers_flag=True, pca_cols=pca_cols)

    factor = result["factor"]
    df_std = standardize_dataframe(df)

    # Use last 10 years for charts
    indicator_cols = [c for c in df.columns if c != "date"]
    latest = df.dropna(subset=indicator_cols, how="all")["date"].max()
    cutoff = latest - pd.DateOffset(years=10)

    factor_win = factor[factor.index >= cutoff]
    df_win = df_std[df_std["date"] >= cutoff]

    fig_factor = factor_chart(factor_win, title=f"{country} — Common Factor")
    fig_theme = theme_chart(df_win, title=f"{country} — Standardised Indicators", yaxis_title="Std Dev")
    fig_heat = surprise_heatmap(result["surprises"], title="Surprises (last 24 months)")

    latest_resid = result["residuals"].dropna(how="all").iloc[-1]
    contribs = compute_contributions(result["loadings"], latest_resid)
    fig_radial = contributions_radial(contribs, title="Factor Contributions (latest)")

    # Combine into a 2×2 HTML page
    html_parts = []
    for fig, title in [
        (fig_factor, "Common Factor"),
        (fig_theme, "Standardised Indicators"),
        (fig_heat, "Surprise Heatmap"),
        (fig_radial, "Factor Contributions"),
    ]:
        html_parts.append(fig.to_html(full_html=False, include_plotlyjs="cdn"))

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{country} Activity — Monitoring Dashboard Snapshot</title>
  <style>
    body {{ font-family: system-ui, sans-serif; background: #f8f9fa; margin: 0; padding: 16px; }}
    h1 {{ font-size: 1.4rem; color: #333; margin-bottom: 4px; }}
    .vintage-badge {{
      display: inline-block; background: #e67e22; color: white;
      font-size: 0.75rem; padding: 2px 8px; border-radius: 3px; margin-bottom: 12px;
    }}
    .subtitle {{ color: #666; font-size: 0.9rem; margin-bottom: 16px; }}
    .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
    .chart-box {{ background: white; border-radius: 8px; padding: 12px;
                  box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
    @media (max-width: 800px) {{ .grid {{ grid-template-columns: 1fr; }} }}
    .back {{ margin-top: 20px; font-size: 0.85rem; }}
    .back a {{ color: #2980b9; }}
  </style>
</head>
<body>
  <h1>{country} Activity Monitor</h1>
  <span class="vintage-badge">Snapshot — PoC vintage</span>
  <p class="subtitle">
    Static export from the monitoring-dashboard. Data as of the last available
    observation in the haver-data repo. Generated by
    <code>scripts/export_snapshot.py</code>.
  </p>
  <div class="grid">
    <div class="chart-box">{html_parts[0]}</div>
    <div class="chart-box">{html_parts[1]}</div>
    <div class="chart-box">{html_parts[2]}</div>
    <div class="chart-box">{html_parts[3]}</div>
  </div>
  <div class="back">
    <a href="../index.html">← Back to demo index</a> ·
    <a href="https://github.com/jasonzhixinglu/monitoring-dashboard">GitHub repo</a>
  </div>
</body>
</html>"""

    out_file.write_text(page)
    print(f"  Written: {out_file}")


def main():
    print("Exporting snapshots...")
    for country, config, theme, filename in EXPORTS:
        print(f"  {country} {theme}...")
        try:
            export_activity(country, config, DOCS_DIR / filename)
        except Exception as e:
            warnings.warn(f"Failed to export {country} {theme}: {e}")
    print("Done. Files in docs/snapshots/")


if __name__ == "__main__":
    main()
